In [1]:
import numpy as numpy
import pandas as pd

In [2]:
data = pd.read_csv("Restaurant_Reviews.tsv", sep="\t", encoding="ISO-8859-1")
data

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [3]:
dataset = pd.read_table("Restaurant_Reviews.tsv")
dataset

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [4]:
import pandas as pd
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

dataset = pd.read_table("Restaurant_Reviews.tsv")

corpus = []

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

for i in range(len(dataset)):

    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])

    review = review.lower()

    review = review.split()

    review = [ps.stem(word) for word in review if word not in stop_words]

    review = ' '.join(review)

    corpus.append(review)

[nltk_data] Downloading package stopwords to C:\Users\anwar
[nltk_data]     salman\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=1500)

X=cv.fit_transform(corpus).toarray()

y=dataset.iloc[:,1].values

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
X,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()

model.fit(X_train,y_train)

GaussianNB()

In [8]:
from sklearn.metrics import accuracy_score

pred=model.predict(X_test)

print("Accuracy =",accuracy_score(y_test,pred))

Accuracy = 0.73

In [9]:
review=["food was amazing"]

review=cv.transform(review).toarray()

print(model.predict(review))

[1]

In [10]:
review=["very bad service"]

review=cv.transform(review).toarray()

print(model.predict(review))

[0]

In [11]:

def predict_review(text):
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    
    review = cv.transform([review]).toarray()
    result = model.predict(review)
    
    if result[0] == 1:
        print("Positive 👍")
    else:
        print("Negative 👎")

predict_review("food was amazing")
predict_review("very bad service")

Positive 👍
Negative 👎

In [ ]:
sample = ["The restaurant was very bad and dirty"]
sample_vec = cv.transform(sample).toarray()
prediction = model.predict(sample_vec)

if prediction[0] == 1:
    print("Positive 😊")
else:
    print("Negative 😠")

Negative 😠

: